name: Setup Node
description: setup node and pnpm

runs:
  using: 'composite'
  steps:

    - name: Setup pnpm
      uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
      with:
        run_install: false
        version: 10

    - name: Install Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 22
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
        cache-dependency-path: 'ui-release/pnpm-lock.yaml'

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/ui-release/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
