name: Setup Go
description: 'Set up Go and Protoc'

inputs:
  token:
    description: 'Optional GitHub token'

runs:
  using: 'composite'

  steps:
    - uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Setup Protoc
      if : ${{ inputs.token }}
      uses: arduino/setup-protoc@v1
      with:
        version: '3.x'
        repo-token: ${{ inputs.token }}
