name: Setup Go
description: 'Set up Go and Protoc'

runs:
  using: 'composite'

  steps:
    - uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Setup Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.x'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

