enableUi: true
enableOpenApi: true
auth:
  enabled: false
  providers:
    - label: google oidc # for internal use; in future may expose as button text
      type: oidc # for futureproofing; only oidc is supported today
      providerUrl: https://accounts.google.com
      clientId: xxxxxxxxxx-xxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
      clientSecret: xxxxxxxxxxxxxxxxxxxxxxx
      scopes:
        - openid
        - profile
        - email
      audience:
      callbackUrl: http://localhost:8080/auth/sso/callback
      passIdToken: false
