name: Download and Build UI
description: Downloads, builds, and copies temporalio/ui from a given SHA

inputs:
  ref:
    description: 'Commit SHA of temporalio/ui to build'
    required: true
  token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Download UI
      uses: actions/checkout@v3
      with:
        repository: temporalio/ui
        ref: ${{ inputs.ref }}
        path: ui-release


    - name: Install dependencies and build UI
      run: |
        cd ui-release
        pnpm install --frozen-lockfile
        pnpm build:server

    - name: Copy UI to server
      run: |
        rm -rf server/proto/dependencies/api
        cp -r ui-release/server/* ./
        rm -rf ui-release
