name: 'Docker Build and Push'
description: 'Build and push Docker images'

inputs:
  images:
    description: 'Docker images'
    required: true
  tags:
    description: 'Docker tags'
    required: true
  labels:
    description: 'Docker labels'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ inputs.tags }}
        labels: ${{ inputs.labels }}
