name: 'Setup Docker'
description: 'Set up Docker Buildx and login to DockerHub'

inputs:
  docker_username:
    description: 'Docker username'
    required: true
  docker_pat:
    description: 'Docker personal access token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2.2.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2.10.0

    - name: Login to DockerHub
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_pat }}
