name: 'Setup Docker'
description: 'Set up Docker Buildx and login to DockerHub'

inputs:
  docker_username:
    description: 'Docker username'
    required: true
  docker_pat:
    description: 'Docker personal access token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_pat }}

