name: Load UI SHA
description: Resolve and validate the temporalio/ui commit SHA

inputs:
  repo:
    description: The repository to resolve the commit SHA from
    required: true
    default: temporalio/ui
  ui_commit_ref:
    description: Commit SHA of temporalio/ui
    required: false
  token:
    description: GitHub token for authentication
    required: true

outputs:
  sha:
    description: The resolved commit SHA (input or latest)
    value: ${{ steps.resolve.outputs.sha }}
  short_sha:
    description: The short 7-char version of the resolved SHA
    value: ${{ steps.resolve.outputs.short_sha }}

runs:
  using: composite
  steps:
    - name: Resolve commit SHA
      id: resolve
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        if [[ -z "${{ inputs.ui_commit_ref }}" ]]; then
          echo "No SHA provided, resolving latest from temporalio/ui..."
          REF="main"
        else
          echo "Using provided SHA: ${{ inputs.ui_commit_ref }}"
          REF="${{ inputs.ui_commit_ref }}"
        fi

        RESOLVED_SHA=$(gh api repos/${{ inputs.repo }}/commits/$REF --jq .sha)

        SHORT_SHA=${RESOLVED_SHA:0:7}
        echo "sha=$RESOLVED_SHA" >> $GITHUB_OUTPUT
        echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT
        echo "RESOLVED_SHA=$RESOLVED_SHA" >> $GITHUB_ENV

