name: Publish Docker image

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  publish_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta for Cloud Release image
        id: meta_release_cloud
        uses: docker/metadata-action@v3
        with:
          images: temporalio/cloud-ui
          tags: |
            type=sha,format=short,event=branch
            latest

      - name: Push Cloud Release image to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          file: cloud.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta_release_cloud.outputs.tags }}
          labels: ${{ steps.meta_release_cloud.outputs.labels }}


