name: Publish Docker image

on:
  push:
    branches:
      - main
  release:
    types:
      - released

jobs:
  publish_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Docker meta for Commit image
        id: meta_commit
        uses: docker/metadata-action@v4
        if: github.event_name == 'push'
        with:
          images: temporaliotest/ui
          tags: |
            type=sha,format=short,event=branch
            latest

      - name: Push Commit image to DockerHub
        uses: docker/build-push-action@v4
        if: github.event_name == 'push'
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta_commit.outputs.tags }}
          labels: ${{ steps.meta_commit.outputs.labels }}

      - name: Docker meta for Release image
        id: meta_release
        uses: docker/metadata-action@v4
        if: github.event_name == 'release'
        with:
          images: temporalio/ui
          tags: |
            type=semver,pattern={{version}}
            latest

      - name: Push Release image to DockerHub
        uses: docker/build-push-action@v4
        if: github.event_name == 'release'
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta_release.outputs.tags }}
          labels: ${{ steps.meta_release.outputs.labels }}

      - name: Docker meta for Release image
        id: cloud_meta_release
        uses: docker/metadata-action@v4
        if: github.event_name == 'release'
        with:
          images: temporalio/cloud-ui
          tags: |
            type=semver,pattern={{version}}
            latest

      - name: Push Release image to DockerHub
        uses: docker/build-push-action@v4
        if: github.event_name == 'release'
        with:
          push: true
          build-args: TEMPORAL_CLOUD_UI=true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.cloud_meta_release.outputs.tags }}
          labels: ${{ steps.cloud_meta_release.outputs.labels }}
